# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-97c4ccff-6bf2-426c-92fc-2922499627b3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-97c4ccff-6bf2-426c-92fc-2922499627b3".device = "/dev/disk/by-uuid/97c4ccff-6bf2-426c-92fc-2922499627b3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FD17-0AAA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # swapDevices =
  #   [ { device = "/dev/mapper/dev-disk-byx2dpartuuid-da2c2ea6x2d323fx2d426ex2d9644x2d328248df2efa"; }
  #   ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
